name: Python package

on:
  push:
    branches: 
      - master
  pull_request:
    branches: 
      - master
      - dev
  release:
    types:
      - created

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Python Poetry Action
      uses: abatilo/actions-poetry@v1.0.0
    - name: Black Code Formatter
      uses: lgeiger/black-action@v1.0.1
    - name: Lint with flake8
      run: |
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings
        flake8 . --count --exit-zero --max-complexity=5 --max-line-length=88 --ignore=E203 --statistics
    - name: Check with Mypy
      uses: jpetrucciani/mypy-check@0.761
      with:
        path: '.'
